### ISSUE TITLE
error: unexpected keyword argument 'root_name' (nbtlib version mismatch)

### ISSUE THREAD

**Issue by LeePC** [4321ba/Galaxy_Jukebox#1]
C:\Users\akrrk\Documents\Galaxy_Jukebox-main>python main.py 1.nbs 1.schem
Traceback (most recent call last):
  File "main.py", line 65, in <module>
    convert(argv[1], argv[2])
  File "main.py", line 60, in convert
    schem.save(out_path)
  File "C:\Users\akrrk\Documents\Galaxy_Jukebox-main\sponge_schematic.py", line 75, in save
    }, gzipped=True, root_name="schem")
TypeError: __init__() got an unexpected keyword argument 'root_name'

fix please....

**Comment by 4321ba** [comment]
hmmm what version of nbtlib do you have? `pip show nbtlib`
I just updated ( [this commit](https://github.com/4321ba/Galaxy_Jukebox/commit/2869eb430af3d9daf78633e1dd70c124e2d2b508), a week ago ) the code to work with nbtlib 2.0.4 instead of 1.12.1

**Comment by LeePC** [comment]
ah.... Thank you ^^

**Comment by 4321ba** [comment]
I'll close this seeing as it seems to be resolved, but if you have any problems be sure to reopen / open another issue ;)
